<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
	<title>XLW - A for the Excel API</title>
	<meta http-equiv='Content-Style-Type' content='text/css' />
    <!--HeaderText--><style type='text/css'><!--
  ul, ol, pre, dl, p { margin-top:0px; margin-bottom:0px; }
  code.escaped { white-space: nowrap; }
  .vspace { margin-top:1.33em; }
  .indent { margin-left:40px; }
  .outdent { margin-left:40px; text-indent:-40px; }
  a.createlinktext { text-decoration:none; border-bottom:1px dotted gray; }
  a.createlink { text-decoration:none; position:relative; top:-0.5em;
    font-weight:bold; font-size:smaller; border-bottom:none; }
  img { border:0px; }
  .editconflict { color:green; 
  font-style:italic; margin-top:1.33em; margin-bottom:1.33em; }

  table.markup { border:2px dotted #ccf; width:90%; }
  td.markup1, td.markup2 { padding-left:10px; padding-right:10px; }
  table.vert td.markup1 { border-bottom:1px solid #ccf; }
  table.horiz td.markup1 { width:23em; border-right:1px solid #ccf; }
  table.markup caption { text-align:left; }
  div.faq p, div.faq pre { margin-left:2em; }
  div.faq p.question { margin:1em 0 0.75em 0; font-weight:bold; }
   
    .frame 
      { border:1px solid #cccccc; padding:4px; background-color:#f9f9f9; }
    .lfloat { float:left; margin-right:0.5em; }
    .rfloat { float:right; margin-left:0.5em; }
a.varlink { text-decoration:none; }

--></style>  <meta name='robots' content='index,follow' />

    <link rel='stylesheet' href='xlw.css' type='text/css' />
	<script type="text/javascript">
	<!-- //
    IE6 = navigator.appVersion.indexOf("MSIE 6.") == -1 ? false : true;
	if (IE6) { 
		document.write("<link href='xlw-ie.css' rel='stylesheet' type='text/css' />");
	}
	//-->
	</script>
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">
</head>

<body>
    <div id='wrapper'>
        <div id='head'></div>
        <div id='version_string'>Release v3.0 |&nbsp Dev v4.0 Beta 2</div>
        <div id='tagline'>A Wrapper for the Excel API</div>
        <div id='content'>
            <div id='col-left'>
                <!--PageLeftFmt-->
                <div id='sidebar'><ul><li><a href='index.shtml'>Home</a>
</li><li><a href='project.shtml'>Project</a>
</li><li><a href='documentation.shtml'>Documentation</a>
</li><li><a href='license.shtml'>License</a>
</li><li><a href='history.shtml'>History</a>
</li><li><a href='YouTube.shtml'>Video Clips</a>
</li></ul>
</div>

<div class="logolist">
<div class="vspace"></div>
<a class="imglink" href="http://www.nazcatech.be"><img src="images/nazcatech.jpg" width="88" height="98" border="0" alt="nazcatech"/></a>
<div class="vspace"></div>
<a class="imglink" href="http://sourceforge.net"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=45222&amp;type=1" width="88" height="31" border="0" alt="SourceForge.net Logo"/></a>
</div>

                <!--/PageLeftFmt-->
            </div>

            <div id='col-right'>
<!--PageText-->
<div id='wikitext'>
<div style='text-align: justify;' > 
