//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include "xlw/MyContainers.h"
#include <xlw/CellMatrix.h>
#include <stdexcept>
#include "cppinterface.h"
#include <xlw/xlwManaged.h>
using namespace System;
using namespace Runtime::InteropServices;
using namespace System;






double mxlw_EchoDate
		(
		double datea
		)
		{
		MANAGED_EXECL_BEGIN
			DateTime date( DateTime::FromOADate(datea ));

			return EchoDate(date );
		MANAGED_EXECL_END
		}

////////////////////////////////////

