//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include "xlw/MyContainers.h"
#include <xlw/CellMatrix.h>
#include <stdexcept>
using namespace xlw;





void // Authenticate
authenticate();





double  //  Echoes Date
mxlw_EchoDate		(
		double date // the Date
 );
