make -f ExampleMakefile DEV=devcpp
make -f ExampleMakefile DEV=gcc-make

"C:\Program Files\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\AutoGenerated\vc7\ExampleAutogenerated.sln  /rebuild Debug    /out ExampleAutogenerated7Debug.log
"C:\Program Files\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\AutoGenerated\vc7\ExampleAutogenerated.sln  /rebuild Release  /out ExampleAutogenerated7Release.log
"C:\Program Files\Microsoft Visual Studio 8\VC\vcpackages\vcbuild.exe" /rebuild    ..\xlw\examples\AutoGenerated\vc8\ExampleAutogenerated.sln  >> ExampleAutogenerated8.log 2>&1 
"C:\Program Files\Microsoft Visual Studio 9.0\VC\vcpackages\vcbuild.exe" /rebuild  ..\xlw\examples\AutoGenerated\vc9\ExampleAutogenerated.sln  >> ExampleAutogenerated9.log 2>&1 

"C:\Program Files\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\Handwritten\vc7\ExampleHandWritten.sln  /rebuild Debug    /out ExampleHandwritten7Debug.log
"C:\Program Files\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe"   ..\xlw\examples\Handwritten\vc7\ExampleHandWritten.sln  /rebuild Release  /out ExampleHandwritten7Release.log
"C:\Program Files\Microsoft Visual Studio 8\VC\vcpackages\vcbuild.exe" /rebuild    ..\xlw\examples\Handwritten\vc8\ExampleHandWritten.sln  >> ExampleHandwritten8.log 2>&1 
"C:\Program Files\Microsoft Visual Studio 9.0\VC\vcpackages\vcbuild.exe" /rebuild  ..\xlw\examples\Handwritten\vc9\ExampleHandWritten.sln  >> ExampleHandwritten9.log 2>&1 

