@SETLOCAL
@IF NOT DEFINED XLW_FOUND_PROGRAMS CALL FindPrograms.bat
@IF ERRORLEVEL 1 ECHO Can't find all required programs & exit /b 1

CALL BuildProjectCpp.bat ..\xlw\examples\Example xlwExampleAutoGenerated
CALL BuildProjectCpp.bat ..\xlw\examples\Handwritten xlwExampleHandwritten
CALL BuildProjectCpp.bat ..\xlw\examples\ObjectCacheDemo xlwExampleObjectCacheDemo
CALL BuildProjectCpp.bat ..\xlw\examples\C++CLR xlwExampleC++CLR
CALL BuildProjectCpp.bat ..\xlw\examples\LoggerDemo xlwExampleLoggerDemo
CALL BuildProjectCpp.bat ..\xlw\examples\C++CLR_password xlwExampleC++CLR_password
CALL BuildProjectCpp.bat "..\xlw\examples\Start Here - Example" xlwExampleStartHere
CALL BuildProjectCpp.bat "..\xlw\examples\MJ - Design Patterns" xlwExampleDesignPatterns
CALL BuildProjectCpp.bat "..\xlw\examples\Commands and Attributes" xlwExampleCommandsAttributes

@ENDLOCAL