

.PHONY : all

all: 
	cd ..\xlw\\build\\$(DEV)  && $(MAKE)  BUILD=DEBUG rebuild >> ..\\..\\..\\BatchBuild\\xlw$(DEV)Debug.log 2>&1 
	cd ..\xlw\\build\\$(DEV)  && $(MAKE)  BUILD=RELEASE rebuild >> ..\\..\\..\\BatchBuild\\xlw$(DEV)Release.log  2>&1 
