//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include "xlw/MyContainers.h"
#include <xlw/CellMatrix.h>
#include <stdexcept>
using namespace xlw;





CellMatrix  //  Obtains historial market data from yahoo
mxlw_GetHistoricDataFromYahoo		(
		std::string symbol, // Yahoo Symbol
		double beginDate, // Begin Date
		double endDate //End Date
 );
double  //  Echoes Date
mxlw_EchoDate		(
		double date // the Date
 );
std::string  //   Computes the SHA1 hash of the input string
mxlw_SHA1Hash		(
		std::string value // The data
 );
